### ISSUE TITLE
RMETAR crashes while processing METAR in loops

### ISSUE THREAD

**Issue by GreenhouseCH** [jwijffels/RMETAR#1] opened 2017-08-25 10:43 UTC
RMETAR is a great tool for decoding METARs in R. Unfortunately, it seems that the DLL is generating some problems if you want to massively decode a list of METARs in a loop. 
I couldn't find a workaround for it. Here is a reproducible example. There is a tendency that RStudio crashes earlier than the R binary itself - with earlier I mean: with shorter loops.

Is there any fix for that? 

I already tried to introduce Sys.sleep() prompts without success. 

The problem happens both in i386 and x64 R interfaces, on all Windows 10 systems I used up to now. 

Kind regards

Bertrán
[minimal.example.R.zip](https://github.com/jwijffels/RMETAR/files/1251625/minimal.example.R.zip)

**Comment by jwijffels** [comment] 2017-08-25 10:59
Hi Bertran, I can't reproduce this on my Linux machine.

**Comment by GreenhouseCH** [comment] 2017-08-25 11:05
Hello

Thanks for your rapid reply. Next level: Does this script work with you?
[RMETAR_OGIMET.zip](https://github.com/jwijffels/RMETAR/files/1251665/RMETAR_OGIMET.zip)

**Comment by jwijffels** [comment] 2017-08-25 11:08
Yes, it does on my machine.

**Comment by GreenhouseCH** [comment] 2017-08-25 11:09
Allright, do you own a Windows machine? I think it has something to do with the dynamic library.

**Comment by jwijffels** [comment] 2017-08-25 11:09
yes, but currently not sitting behind one.

**Comment by GreenhouseCH** [comment] 2017-08-25 11:14
It would be great if you could test it there and report.

**Comment by jwijffels** [comment] 2017-08-25 19:53
I can confirm the crash on Windows.

**Comment by GreenhouseCH** [comment] 2017-08-28 06:53
Thanks for checking. Is there any way to fix this?

**Comment by jwijffels** [comment] 2017-08-29 07:17
Yes, but it is on a long todo list

**Comment by GreenhouseCH** [comment] 2017-08-29 11:09
Allright. Would be great.

**Comment by jwijffels** [comment] 2017-09-04 09:33
I think the best to fix this is to rewrite this using Rcpp but this requires quite some work.

**Comment by andrie** [comment] 2019-08-09 16:15
I think we can close this, since it will be addressed by #8

**Comment by jwijffels** [comment] 2019-08-09 17:53
Yes DEV version which uses https://github.com/flightaware/mdsplib no longer crashes on large number of METAR reports.

**Closed as completed by jwijffels** 2019-08-09 17:53 UTC
